spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: localhost
    port: 5672
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username:
    password:
